name: verbrauchs_app
description: A new Flutter project.

version: 1.0.4+4

environment:
  sdk: '>=3.4.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  http: ^1.2.1
  shared_preferences: ^2.2.3
  sqflite: ^2.3.3+1
  path_provider: ^2.1.3
  image_picker: ^1.1.2
  permission_handler: ^11.4.0  # Aktualisiert auf kompatible neuere Version
  share_plus: ^10.1.4 
  csv: ^6.0.0
  excel: ^4.0.6
  pdf: ^3.11.1
  printing: ^5.13.4
  fl_chart: ^1.0.0  # Aktualisiert auf neuere Version
  flutter_local_notifications: ^17.2.4  # Aktualisiert auf neuere Version
  google_mlkit_text_recognition: ^0.15.0 
  timezone: ^0.9.4
  intl: ^0.19.0
  file_picker: ^10.3.2  # Aktualisiert auf neuere Version
  path: ^1.9.0
  equatable: ^2.0.5

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0  # Aktualisiert auf neuere Version (aber kompatibel)

flutter:
  uses-material-design: true