name: verbrauchs_app
description: A new Flutter project.

version: 1.0.4+4

environment:
  sdk: '>=3.4.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  
  # Aktualisierte Pakete
  http: ^1.2.1
  shared_preferences: ^2.2.3
  sqflite: ^2.3.3+1
  path_provider: ^2.1.3
  image_picker: ^1.1.2
  permission_handler: ^11.3.1
  share_plus: 10.1.4
  csv: ^6.0.0
  excel: ^4.0.6
  pdf: ^3.11.1
  printing: ^5.13.4
  fl_chart: ^0.68.0
  flutter_local_notifications: ^17.2.2
  google_mlkit_text_recognition: ^0.13.0
  timezone: ^0.9.4
  intl: ^0.19.0
  file_picker: ^8.0.6
  path: ^1.9.0
  equatable: ^2.0.7

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true